### ISSUE TITLE
Add Kotlin suspending function variant to fold

### ISSUE THREAD

**Issue by sdeleuze** [making/yavi#14]
I think it would be useful to add a `suspend fun <L, R, U> Either<L, R>.fold(leftMapper: suspend (L) -> U, rightMapper: suspend (R) -> U)` Kotlin extension in order to be able to use suspending functions here.

**Comment by making** [comment]
I'm not familiar with Coroutines. 

Does it look like

```kotlin
suspend fun <L, R, U> Either<L, R>.fold(leftMapper: suspend (L) -> U, rightMapper: suspend (R) -> U) = fold({
    GlobalScope.async {
        leftMapper.invoke(it)
    }
}, {
    GlobalScope.async {
        rightMapper.invoke(it)
    }
})
```
?

**Comment by sdeleuze** [comment]
With package private `left` and `right` field suggested [here](https://github.com/making/yavi/issues/15#issuecomment-489599377), it should be just:

```
suspend fun <L, R, U> Either<L, R>.fold(leftMapper: suspend (L) -> U, rightMapper: suspend (R) -> U) =
    if (isLeft) leftMapper.invoke(left) else rightMapper.invoke(right)
```

It is not equivalent to use `GlobalScope.async` so we have to duplicate here, we can't reuse original `fold`.

**Comment by making** [comment]
Cool, thanks!

Because new `fold` method's signature conflicts existing one, `<>` parameters seem to be explicitly specified. 

![image](https://user-images.githubusercontent.com/106908/57227913-7b9a1900-704d-11e9-87bd-1dddc9e4230e.png)

![image](https://user-images.githubusercontent.com/106908/57227931-8359bd80-704d-11e9-84ba-970278d073d4.png)

Is it better to rename to maybe `foldAsync` ?

**Comment by sdeleuze** [comment]
Suspending functions are named by convention `awaitSomething` or `actionAndAwait`. For this one this is not 100% clear but I think  `awaitFold` would be ok.

**Comment by making** [comment]
I'll use `awaitSomething`, thanks!

**Comment by making** [comment]
4a688ce is a mistake
